# This workflow will build and push a node.js application to an Azure Web App when a release is created.

on:
  push:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: some-recipes    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'backend'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '12.x'                # set this to the node version to use
  SECRET: ${{ secrets.SECRET}}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
      
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        cd backend
        npm install
        npm run build
        rm -rf build 
        rm -rf dist/build
        cd ../frontend
        npm install
        npm run build --prod
        cp -r build ../backend/
        cp -r build ../backend/dist
        
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
